---
- name: Clean up the environment
  file:
    dest: "{{ lightsail_venv }}"
    state: absent
  when: clean_environment

- name: Install requirements
  pip:
    name:
      - boto>=2.5
      - boto3
    state: latest
    virtualenv: "{{ lightsail_venv }}"
    virtualenv_python: python2.7
