---

- name: FreeBSD / HardenedBSD | Enable dnsmasq
  lineinfile: dest=/etc/rc.conf regexp=^dnsmasq_enable= line='dnsmasq_enable="YES"'

- name: The dnsmasq additional directories created
  file:
    dest: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ config_prefix|default('/') }}etc/dnsmasq.d"
