---
- pause:
    prompt: |
      Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
      Note: Make sure to use an IAM user with an acceptable policy attached (see https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md)
    echo: false
  register: _aws_access_key
  when:
     - aws_access_key is undefined
     - lookup('env','AWS_ACCESS_KEY_ID')|length <= 0

- pause:
    prompt: |
      Enter your aws_secret_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
    echo: false
  register: _aws_secret_key
  when:
    - aws_secret_key is undefined
    - lookup('env','AWS_SECRET_ACCESS_KEY')|length <= 0

- set_fact:
    access_key: "{{ aws_access_key | default(_aws_access_key.user_input|default(None)) | default(lookup('env','AWS_ACCESS_KEY_ID'), true) }}"
    secret_key: "{{ aws_secret_key | default(_aws_secret_key.user_input|default(None)) | default(lookup('env','AWS_SECRET_ACCESS_KEY'), true) }}"

- block:
  - name: Get regions
    aws_region_facts:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      region: us-east-1
    register: _aws_regions

  - name: Set facts about the regions
    set_fact:
      aws_regions: "{{ _aws_regions.regions | sort(attribute='region_name') }}"

  - name: Set the default region
    set_fact:
      default_region: >-
        {% for r in aws_regions %}
        {%- if r['region_name'] == "us-east-1" %}{{ loop.index }}{% endif %}
        {%- endfor %}

  - pause:
      prompt: |
        What region should the server be located in?
        (https://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region)
          {% for r in aws_regions %}
          {{ loop.index }}. {{ r['region_name'] }}
          {% endfor %}

        Enter the number of your desired region
        [{{ default_region }}]
    register: _algo_region
  when: region is undefined
