---
algo_local_dns: false
listen_port: "{% if algo_local_dns %}5353{% else %}53{% endif %}"
# the version used if the latest unavailable (in case of Github API rate limited)
dnscrypt_proxy_version: 2.0.10
apparmor_enabled: true
dns_encryption: true
ipv6_support: false
dnscrypt_servers:
  ipv4:
    - cloudflare
  ipv6:
    - cloudflare-ipv6
